"""initial control-plane schema

Revision ID: 09a75fd21cf8
Revises: 
Create Date: 2026-06-29 22:37:22.348494
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '09a75fd21cf8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plugin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('contract_version', sa.String(length=20), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_resource_id'), ['resource_id'], unique=False)

    op.create_table('environment_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug')
    )
    with op.batch_alter_table('environment_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_template_organization_id'), ['organization_id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_organization_id'), ['organization_id'], unique=False)

    op.create_table('environment_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('api_version', sa.String(length=100), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['environment_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_number')
    )
    with op.batch_alter_table('environment_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_version_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_version_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_version_template_id'), ['template_id'], unique=False)

    op.create_table('user_role_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'organization_id')
    )
    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_assignment_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_assignment_user_id'), ['user_id'], unique=False)

    op.create_table('exercise',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('environment_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=40), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_version_id'], ['environment_version.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['environment_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_environment_version_id'), ['environment_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_organization_id'), ['organization_id'], unique=False)

    op.create_table('artifact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_organization_id'), ['organization_id'], unique=False)

    op.create_table('deployment_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('environment_version_id', sa.Uuid(), nullable=False),
    sa.Column('version_content_hash', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_content_hash', sa.String(length=80), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_version_id'], ['environment_version.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_plan_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_plan_organization_id'), ['organization_id'], unique=False)

    op.create_table('environment_instance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('team_index', sa.Integer(), nullable=False),
    sa.Column('instance_ref', sa.String(length=120), nullable=False),
    sa.Column('team_ref', sa.String(length=120), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'team_index')
    )
    with op.batch_alter_table('environment_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_instance_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_instance_organization_id'), ['organization_id'], unique=False)

    op.create_table('workflow_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('dispatch_mode', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('target_instance_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_run_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_run_organization_id'), ['organization_id'], unique=False)

    op.create_table('simulated_network',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('team_ref', sa.String(length=120), nullable=True),
    sa.Column('isolated', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['environment_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulated_network', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_network_instance_id'), ['instance_id'], unique=False)

    op.create_table('simulated_node',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('network_ref', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['environment_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulated_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_node_instance_id'), ['instance_id'], unique=False)

    op.create_table('simulated_topology_edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=False),
    sa.Column('target_ref', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['environment_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulated_topology_edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_topology_edge_instance_id'), ['instance_id'], unique=False)

    # ### end Alembic commands ###

    _install_immutability_trigger()


# --- Immutability enforcement (ADR-002, Charter Invariants 2, 10) -------------
# PostgreSQL-only DB-level guard so even raw SQL cannot mutate a published
# environment version or update/delete an audit event. The portable ORM-level
# guard in secp_api.immutability covers SQLite (and is defense in depth on PG).

def _install_immutability_trigger() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        """
        CREATE OR REPLACE FUNCTION secp_block_version_mutation()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.spec IS DISTINCT FROM OLD.spec
               OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
               OR NEW.version_number IS DISTINCT FROM OLD.version_number
               OR NEW.api_version IS DISTINCT FROM OLD.api_version THEN
                RAISE EXCEPTION 'environment_version is immutable after creation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER secp_environment_version_immutable
        BEFORE UPDATE ON environment_version
        FOR EACH ROW EXECUTE FUNCTION secp_block_version_mutation();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION secp_block_audit_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_event records are immutable and append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER secp_audit_event_immutable
        BEFORE UPDATE OR DELETE ON audit_event
        FOR EACH ROW EXECUTE FUNCTION secp_block_audit_mutation();
        """
    )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS secp_audit_event_immutable ON audit_event")
        op.execute("DROP TRIGGER IF EXISTS secp_environment_version_immutable ON environment_version")
        op.execute("DROP FUNCTION IF EXISTS secp_block_audit_mutation")
        op.execute("DROP FUNCTION IF EXISTS secp_block_version_mutation")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulated_topology_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_topology_edge_instance_id'))

    op.drop_table('simulated_topology_edge')
    with op.batch_alter_table('simulated_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_node_instance_id'))

    op.drop_table('simulated_node')
    with op.batch_alter_table('simulated_network', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_network_instance_id'))

    op.drop_table('simulated_network')
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_run_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_run_exercise_id'))

    op.drop_table('workflow_run')
    with op.batch_alter_table('environment_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_instance_organization_id'))
        batch_op.drop_index(batch_op.f('ix_environment_instance_exercise_id'))

    op.drop_table('environment_instance')
    with op.batch_alter_table('deployment_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_plan_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_plan_exercise_id'))

    op.drop_table('deployment_plan')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_organization_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_exercise_id'))

    op.drop_table('artifact')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_organization_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_environment_version_id'))

    op.drop_table('exercise')
    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_assignment_organization_id'))

    op.drop_table('user_role_assignment')
    with op.batch_alter_table('environment_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_version_template_id'))
        batch_op.drop_index(batch_op.f('ix_environment_version_organization_id'))
        batch_op.drop_index(batch_op.f('ix_environment_version_content_hash'))

    op.drop_table('environment_version')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_organization_id'))

    op.drop_table('team')
    with op.batch_alter_table('environment_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_template_organization_id'))

    op.drop_table('environment_template')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_action'))

    op.drop_table('audit_event')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_organization_id'))

    op.drop_table('app_user')
    op.drop_table('role')
    op.drop_table('plugin')
    op.drop_table('organization')
    # ### end Alembic commands ###
