"""workflow run discovery linkage

Revision ID: 29900a63b28f
Revises: c1f0865cf71b
Create Date: 2026-06-30 14:06:17.909566
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '29900a63b28f'
down_revision: str | None = 'c1f0865cf71b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_target_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('snapshot_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('workflow_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('exercise_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_workflow_run_execution_target_id'), ['execution_target_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_workflow_run_execution_target', 'execution_target',
            ['execution_target_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workflow_run_execution_target', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workflow_run_execution_target_id'))
        batch_op.alter_column('exercise_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('workflow_id')
        batch_op.drop_column('snapshot_id')
        batch_op.drop_column('execution_target_id')

    # ### end Alembic commands ###
