"""provisioning manifests and operations

Revision ID: 7f15807ffed4
Revises: d4c2e7f9a8b1
Create Date: 2026-06-30 17:33:19.052235
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '7f15807ffed4'
down_revision: str | None = 'd4c2e7f9a8b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_manifest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_plan_id', sa.Uuid(), nullable=False),
    sa.Column('execution_target_id', sa.Uuid(), nullable=False),
    sa.Column('target_config_hash', sa.String(length=80), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_plan_id'], ['deployment_plan.id'], ),
    sa.ForeignKeyConstraint(['execution_target_id'], ['execution_target.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provisioning_manifest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provisioning_manifest_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_manifest_deployment_plan_id'), ['deployment_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_manifest_execution_target_id'), ['execution_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_manifest_organization_id'), ['organization_id'], unique=False)

    op.create_table('provisioning_operation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('manifest_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('runner', sa.String(length=60), nullable=False),
    sa.Column('operation_ref', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['provisioning_manifest.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('provisioning_operation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provisioning_operation_manifest_id'), ['manifest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_operation_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provisioning_operation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provisioning_operation_organization_id'))
        batch_op.drop_index(batch_op.f('ix_provisioning_operation_manifest_id'))

    op.drop_table('provisioning_operation')
    with op.batch_alter_table('provisioning_manifest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provisioning_manifest_organization_id'))
        batch_op.drop_index(batch_op.f('ix_provisioning_manifest_execution_target_id'))
        batch_op.drop_index(batch_op.f('ix_provisioning_manifest_deployment_plan_id'))
        batch_op.drop_index(batch_op.f('ix_provisioning_manifest_content_hash'))

    op.drop_table('provisioning_manifest')
    # ### end Alembic commands ###
