"""execution targets, inventory snapshots, reservations

Revision ID: c1f0865cf71b
Revises: b2f1a9c7d3e4
Create Date: 2026-06-30 13:50:33.218682
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = 'c1f0865cf71b'
down_revision: str | None = 'b2f1a9c7d3e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_target',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=80), nullable=False),
    sa.Column('secret_ref', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scope_policy', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_target', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_target_config_hash'), ['config_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_target_organization_id'), ['organization_id'], unique=False)

    op.create_table('address_space_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('execution_target_id', sa.Uuid(), nullable=False),
    sa.Column('cidr_block', sa.String(length=64), nullable=False),
    sa.Column('subnet_prefix', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_target_id'], ['execution_target.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_space_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_space_policy_execution_target_id'), ['execution_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_space_policy_organization_id'), ['organization_id'], unique=False)

    op.create_table('provider_inventory_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('execution_target_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('plugin_version', sa.String(length=40), nullable=False),
    sa.Column('target_config_hash', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_target_id'], ['execution_target.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_inventory_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_inventory_snapshot_execution_target_id'), ['execution_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_inventory_snapshot_organization_id'), ['organization_id'], unique=False)

    op.create_table('provider_inventory_resource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('provider_external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('parent_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['provider_inventory_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_inventory_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_inventory_resource_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_inventory_resource_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('network_reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('execution_target_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=True),
    sa.Column('team_ref', sa.String(length=120), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_target_id'], ['execution_target.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_target_id', 'cidr')
    )
    with op.batch_alter_table('network_reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_reservation_execution_target_id'), ['execution_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_reservation_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_reservation_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('deployment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_target_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('target_config_hash', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key(
            'fk_deployment_plan_execution_target', 'execution_target',
            ['execution_target_id'], ['id'],
        )

    # Backfill any pre-existing NULL attributes before enforcing NOT NULL.
    op.execute("UPDATE environment_network SET attributes = '{}' WHERE attributes IS NULL")
    with op.batch_alter_table('environment_network', schema=None) as batch_op:
        batch_op.alter_column('attributes',
               existing_type=sa.JSON(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_simulated_network_instance_id'))
        batch_op.create_index(batch_op.f('ix_environment_network_instance_id'), ['instance_id'], unique=False)

    with op.batch_alter_table('environment_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_node_instance_id'))
        batch_op.create_index(batch_op.f('ix_environment_node_instance_id'), ['instance_id'], unique=False)

    with op.batch_alter_table('environment_topology_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_topology_edge_instance_id'))
        batch_op.create_index(batch_op.f('ix_environment_topology_edge_instance_id'), ['instance_id'], unique=False)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_target_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_exercise_execution_target_id'), ['execution_target_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_exercise_execution_target', 'execution_target',
            ['execution_target_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercise_execution_target', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exercise_execution_target_id'))
        batch_op.drop_column('execution_target_id')

    with op.batch_alter_table('environment_topology_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_topology_edge_instance_id'))
        batch_op.create_index(batch_op.f('ix_simulated_topology_edge_instance_id'), ['instance_id'], unique=False)

    with op.batch_alter_table('environment_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_node_instance_id'))
        batch_op.create_index(batch_op.f('ix_simulated_node_instance_id'), ['instance_id'], unique=False)

    with op.batch_alter_table('environment_network', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_network_instance_id'))
        batch_op.create_index(batch_op.f('ix_simulated_network_instance_id'), ['instance_id'], unique=False)
        batch_op.alter_column('attributes',
               existing_type=sa.JSON(),
               nullable=True)

    with op.batch_alter_table('deployment_plan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deployment_plan_execution_target', type_='foreignkey')
        batch_op.drop_column('target_config_hash')
        batch_op.drop_column('execution_target_id')

    with op.batch_alter_table('network_reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_reservation_organization_id'))
        batch_op.drop_index(batch_op.f('ix_network_reservation_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_network_reservation_execution_target_id'))

    op.drop_table('network_reservation')
    with op.batch_alter_table('provider_inventory_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_inventory_resource_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_provider_inventory_resource_organization_id'))

    op.drop_table('provider_inventory_resource')
    with op.batch_alter_table('provider_inventory_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_inventory_snapshot_organization_id'))
        batch_op.drop_index(batch_op.f('ix_provider_inventory_snapshot_execution_target_id'))

    op.drop_table('provider_inventory_snapshot')
    with op.batch_alter_table('address_space_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_space_policy_organization_id'))
        batch_op.drop_index(batch_op.f('ix_address_space_policy_execution_target_id'))

    op.drop_table('address_space_policy')
    with op.batch_alter_table('execution_target', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_target_organization_id'))
        batch_op.drop_index(batch_op.f('ix_execution_target_config_hash'))

    op.drop_table('execution_target')
    # ### end Alembic commands ###
